name: comb-pool-cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - torchaudio
  - pytorch
  - torchvision
  - cpuonly
  - tqdm
  - matplotlib
  - pandas
  - scikit-learn
  - tensorboard
