name: comb-pool-cuda
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - torchaudio
  - pytorch
  - cudatoolkit=10.2
  - torchvision
  - tqdm
  - matplotlib
  - pandas
  - scikit-learn
  - tensorboard
